# Generated by Django 4.1.7 on 2023-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Pendiente por revisar'), (2, 'Revisado')], default=1),
        ),
    ]
